### PR TITLE
chore: upgrade to latest @dhis2/cli-style

### PR DESCRIPTION
**Pull request by turban**
I'm on thin ice here, but I've tried to follow: 
https://cli-style.dhis2.nu/#/migrate-guide
https://cli-style.dhis2.nu/#/getting-started

I've been running:
yarn add @dhis2/cli-style
npx d2-style install project/js --force

Checks don't seem to run on commit any longer.

### CODE REVIEW

**Comment by amcgee** [comment]
@varl is the expert here, I'm not sure why the hooks wouldn't work.

**Comment by varl** [comment]
What you did looks good. :+1: 

I've seen some instances where I had to purge `node_modules` and `.git/hooks` and re-run `yarn install` to make it work though. 

E.g. this makes it all work for me:

```
varl@jessika:~/dev/dhis2/libs/maps-gl$ rm -r node_modules/
varl@jessika:~/dev/dhis2/libs/maps-gl$ rm -r .git/hooks/*
varl@jessika:~/dev/dhis2/libs/maps-gl$ yarn install
varl@jessika:~/dev/dhis2/libs/maps-gl$ vim package.json
varl@jessika:~/dev/dhis2/libs/maps-gl$ git add -p 
diff --git a/package.json b/package.json
index 33674aa..37569f6 100644
--- a/package.json
+++ b/package.json
@@ -64,6 +64,7 @@
         "format": "yarn format:js && yarn format:text"
     },
     "jest": {
+        "foo": "bar",
         "setupFiles": [
             "./jest.stub.js"
         ],
Stage this hunk [y,n,q,a,d,e,?]? y

varl@jessika:~/dev/dhis2/libs/maps-gl$ git commit -m 'test'
husky > pre-commit (node v12.15.0)
d2-style > javascript 
No matching staged javascript files for pattern "**/*.{js,jsx,ts,tsx}" 
d2-style > structured-text 
Checked 1 text file(s) 
husky > commit-msg (node v12.15.0)
d2-style > commit 
⧗   input: test
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by turban** [comment]
Hmm still not working here @varl 

`
hoop:maps-gl bjornadm$ git checkout chore/d2-style-upgrade
Switched to branch 'chore/d2-style-upgrade'
Your branch is up-to-date with 'origin/chore/d2-style-upgrade'.
hoop:maps-gl bjornadm$ git pull
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/dhis2/maps-gl
 * [new branch]      dependabot/npm_and_yarn/husky-4.2.3 -> origin/dependabot/npm_and_yarn/husky-4.2.3
Already up-to-date.
hoop:maps-gl bjornadm$ rm -r node_modules/
hoop:maps-gl bjornadm$ rm -r .git/hooks/*
rm: .git/hooks/*: No such file or directory
hoop:maps-gl bjornadm$ yarn install
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
 
...

git add -p 
diff --git a/package.json b/package.json
index d2f86bc..33674aa 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
     "name": "@dhis2/maps-gl",
     "version": "1.0.3",
-    "description": "A WebGL rendering engine for DHIS2 maps based on Mapbox GL JS",
+    "description": "A WebGL rendering engine for DHIS2 maps based on Mapbox GL JS.",
     "publishConfig": {
         "access": "public"
     },
Stage this hunk [y,n,q,a,d,/,e,?]? y

hoop:maps-gl bjornadm$ git commit -m 'test'
[chore/d2-style-upgrade 07c7ad3] test
 1 file changed, 1 insertion(+), 1 deletion(-)
hoop:maps-gl bjornadm$ 

`

**Comment by varl** [comment]
Could you post the output of `ls -la .git/hooks` after the `yarn install`?

**Comment by amcgee** [comment]
I'm going to go ahead and close this as it is very old now - @turban if we still need to upgrade cli-style here I can help to do that?

**Pull request closed without merging**
